
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.apalis-codec]]
version = "0.1.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.apalis-core]]
version = "1.0.0-rc.3"
criteria = "safe-to-deploy"

[[exemptions.async-nats]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.55"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.9.4"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.5"
criteria = "safe-to-deploy"

[[exemptions.displaydoc]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.form_urlencoded]]
version = "1.2.2"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-timer]]
version = "3.0.3"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.icu_collections]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_locale_core]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_normalizer_data]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.icu_properties]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.icu_properties_data]]
version = "2.1.2"
criteria = "safe-to-deploy"

[[exemptions.icu_provider]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.idna]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.idna_adapter]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.181"
criteria = "safe-to-deploy"

[[exemptions.litemap]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.8.0"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.num-conv]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.openssl-probe]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.5"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.12"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.2"
criteria = "safe-to-deploy"

[[exemptions.pin-project]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-internal]]
version = "1.1.10"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.13.1"
criteria = "safe-to-deploy"

[[exemptions.potential_utf]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.44"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.12.3"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.9"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.23.36"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.8"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.9"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.11.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.149"
criteria = "safe-to-deploy"

[[exemptions.serde_nanos]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.serde_repr]]
version = "0.1.20"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.signal-hook-registry]]
version = "1.4.8"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.15.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.114"
criteria = "safe-to-deploy"

[[exemptions.synstructure]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.18"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.47"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.27"
criteria = "safe-to-deploy"

[[exemptions.tinystr]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.49.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.4"
criteria = "safe-to-deploy"

[[exemptions.tokio-stream]]
version = "0.1.18"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.18"
criteria = "safe-to-deploy"

[[exemptions.tower-layer]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.tryhard]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.23"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.url]]
version = "2.5.8"
criteria = "safe-to-deploy"

[[exemptions.utf8_iter]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.53.5"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.writeable]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.yoke]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.yoke-derive]]
version = "0.8.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.39"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.39"
criteria = "safe-to-deploy"

[[exemptions.zerofrom]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zerofrom-derive]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-deploy"

[[exemptions.zerotrie]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.zerovec]]
version = "0.11.5"
criteria = "safe-to-deploy"

[[exemptions.zerovec-derive]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.zmij]]
version = "1.0.20"
criteria = "safe-to-deploy"
